spring:
  application:
    name: data-quality-service

  datasource:
    postgres:
      url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      driver-class-name: org.postgresql.Driver

    clickhouse:
      url: jdbc:clickhouse://${CLICKHOUSE_HOST}:${CLICKHOUSE_PORT}/${CLICKHOUSE_DB}
      username: ${CLICKHOUSE_USER}
      password: ${CLICKHOUSE_PASSWORD}
      driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
