spring:
  application:
    name: kafka-producer-service

  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false

app:
  kafka:
    message-send-interval-ms: ${KAFKA_SEND_INTERVAL_MS:1000}