spring:
  application:
    name: kafka-consumer-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:validation-sidecar}
      auto-offset-reset: latest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.fasterxml.jackson.databind.JsonNode
        spring.json.use.type.headers: false

  main:
    allow-bean-definition-overriding: true

app:
  validator:
    base-url: ${VALIDATOR_BASE_URL}
  kafka:
    topics:
      - name: "ecom.order.placed"
        capacity: 1000
        batch-size: 100
      - name: "ecom.product.catalog.updated"
        capacity: 1000
        batch-size: 200
      - name: "ecom.payment.transaction"
        capacity: 1000
        batch-size: 150

  buffer:
    flush-interval-ms:
      10_000