services:
  producer:
    container_name: kafka-producer
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_SEND_INTERVAL_MS: ${KAFKA_SEND_INTERVAL_MS}
    restart: on-failure
    networks:
      - kafka-net

networks:
  kafka-net:
    external: true
