# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.grpc import validation_pb2 as app_dot_grpc_dot_validation__pb2


class ValidationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Validate = channel.unary_unary(
                '/app.grpc.ValidationService/Validate',
                request_serializer=app_dot_grpc_dot_validation__pb2.ValidationRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_validation__pb2.ValidationResponse.FromString,
                )


class ValidationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Validate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ValidationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Validate': grpc.unary_unary_rpc_method_handler(
                    servicer.Validate,
                    request_deserializer=app_dot_grpc_dot_validation__pb2.ValidationRequest.FromString,
                    response_serializer=app_dot_grpc_dot_validation__pb2.ValidationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'app.grpc.ValidationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ValidationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Validate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/app.grpc.ValidationService/Validate',
            app_dot_grpc_dot_validation__pb2.ValidationRequest.SerializeToString,
            app_dot_grpc_dot_validation__pb2.ValidationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
